### ISSUE TITLE
Remove Frontify API access token

### ISSUE THREAD

**Issue by frassinier** [DellSoftwareGroup/Web-DSG#1]
Be careful, you should remove your Frontify API access token from this repository otherwise anyone can override your patterns! [Here is an example](https://github.com/frassinier/frontify-bootstrap#configuration)

**Comment by edooward** [comment]
Fabien, thank you for pointing out that we have sensitive information on our github repository. We will remove it and re-generate the key. By the way, how did you find this out?

**Comment by frassinier** [comment]
I was looking for some `frontify-api` impl with Github search bar :)

**Comment by edooward** [comment]
Fabien, ah I have never used that feature to search for other github projects. Good to know. Thanks again for your help.
